<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'Psr\\Http\\Message\\ResponseFactoryInterface' => 'get1',
);

    protected function get1()
    {
        return $this->resolveFactory(static fn (\Psr\Container\ContainerInterface $container) => $container->get(\Slim\Psr7\Factory\ResponseFactory::class), 'Psr\\Http\\Message\\ResponseFactoryInterface');
    }

}
